# Generated by Django 3.2.5 on 2021-07-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='UnitPrice',
            field=models.IntegerField(default=0),
        ),
    ]
