# Generated by Django 3.2.5 on 2021-07-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_alter_roomtype_unitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstatus',
            name='RoomCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Room.room'),
        ),
    ]
