# Generated by Django 3.2.4 on 2021-06-28 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('CustomerCode', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=100)),
                ('Username', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=50)),
                ('ID_No', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('PhoneNumber', models.IntegerField()),
                ('Description', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('StaffCode', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=100)),
                ('Username', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=50)),
                ('HotelCode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Hotel.hotelmodel')),
            ],
        ),
    ]
