# Generated by Django 3.2.4 on 2021-06-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210628_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='PhoneNumber',
            field=models.CharField(max_length=30),
        ),
    ]
