# Generated by Django 3.2.4 on 2021-06-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_customeruser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='Description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
