# Generated by Django 3.2.4 on 2021-06-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_customeruser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='Description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
