# Generated by Django 3.2.4 on 2021-06-28 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Room', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('RoomBookingCode', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('BookingDate', models.DateField()),
                ('UnitPrice', models.IntegerField()),
                ('Description', models.CharField(default='', max_length=100)),
                ('Status', models.IntegerField(choices=[(1, 'Đã xác nhận'), (2, 'Chưa xác nhận')], max_length=1)),
                ('CustomerCode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.customeruser')),
                ('RoomTypeCode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Room.roomtype')),
            ],
        ),
    ]
