# Generated by Django 3.2.5 on 2021-07-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_alter_roombooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='UnitPrice',
            field=models.IntegerField(default=0),
        ),
    ]
