# Generated by Django 3.2.4 on 2021-06-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('HotelCode', models.AutoField(primary_key=True, serialize=False)),
                ('HotelName', models.CharField(default='', max_length=50)),
                ('StarType', models.IntegerField(default=0)),
                ('HouseNumber', models.IntegerField(default=0)),
                ('Street', models.CharField(default='', max_length=50)),
                ('District', models.CharField(default='', max_length=50)),
                ('City', models.CharField(default='', max_length=50)),
                ('AveragePrice', models.FloatField(default=0)),
                ('Description', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
