# Generated by Django 3.2.4 on 2021-06-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_alter_hotelmodel_startype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmodel',
            name='StarType',
            field=models.IntegerField(),
        ),
    ]
