# Generated by Django 3.2.4 on 2021-07-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_alter_hotelmodel_startype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmodel',
            name='AveragePrice',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='StarType',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
