# Generated by Django 3.2.5 on 2021-07-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_alter_hotelmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmodel',
            name='AveragePrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
